
// HELPER! (I'm not bothered to make a lambda function and deploy!!!)
const emergencyNumbers = {
    "Afghanistan": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Albania": {"ambulance": "17", "fire": "18", "police": "19"},
    "Algeria": {"ambulance": "21606666", "fire": "14", "police": "17"},
    "American Samoa": {"ambulance": "911", "fire": null, "police": null},
    "Andorra": {"ambulance": "118", "fire": "118", "police": "110"},
    "Angola": {"ambulance": "118", "fire": "118", "police": "110"},
    "Antigua & Barbuda": {"ambulance": "999, 911", "fire": null, "police": null},
    "Argentina": {"ambulance": "101", "fire": "107", "police": "101"},
    "Armenia": {"ambulance": "103", "fire": null, "police": null},
    "Aruba": {"ambulance": "911", "fire": null, "police": null},
    "Ascension Island": {"ambulance": "6000", "fire": "911", "police": "6666"},
    "Australia": {"ambulance": "000 (112 on cell phone)", "fire": null, "police": null},
    "Austria": {"ambulance": "112, 122", "fire": null, "police": null},
    "Azerbaijan (Baku)": {"ambulance": "03", "fire": "01", "police": "02"},
    "Bahamas": {"ambulance": "911", "fire": null, "police": null},
    "Bahrain": {"ambulance": "999", "fire": null, "police": null},
    "Bali": {"ambulance": "112", "fire": "118", "police": null},
    "Bangladesh (Dhaka)": {"ambulance": "199", "fire": "9 555 555", "police": "866 551‐3"},
    "Barbados": {"ambulance": "115, 119", "fire": "113, 119", "police": "112, 119"},
    "Belgium": {"ambulance": "112 (cell)/101", "fire": null, "police": null},
    "Belarus": {"ambulance": "03", "fire": "01", "police": "02"},
    "Belize": {"ambulance": "911", "fire": null, "police": null},
    "Benin": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Bermuda": {"ambulance": "911", "fire": null, "police": null},
    "Bhutan": {"ambulance": "110", "fire": "112", "police": "113"},
    "Bolivia": {"ambulance": "911", "fire": null, "police": null},
    "Bonaire": {"ambulance": "911", "fire": null, "police": null},
    "Bosnia‐Herzegovina": {"ambulance": "124", "fire": "123", "police": "122"},
    "Botswana": {"ambulance": "997, 911", "fire": null, "police": null},
    "Brazil": {"ambulance": "911", "fire": null, "police": null},
    "Bosnia": {"ambulance": "94", "fire": "93", "police": "92"},
    "British Virgin Islands": {"ambulance": "999", "fire": null, "police": null},
    "Brunei": {"ambulance": "991", "fire": "995", "police": "993"},
    "Bulgaria": {"ambulance": "150", "fire": "160", "police": "166"},
    "Burkina Faso": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Burma/Myanmar": {"ambulance": "999", "fire": null, "police": null},
    "Burundi": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Cambodia": {"ambulance": "119", "fire": "118", "police": "117"},
    "Cameroon": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Canada": {"ambulance": "911", "fire": null, "police": null},
    "Canary Islands": {"ambulance": "112", "fire": null, "police": null},
    "Cape Verde": {"ambulance": "130", "fire": "131", "police": "132"},
    "Cayman Islands": {"ambulance": "911", "fire": null, "police": null},
    "Central African Republic": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Chad": {"ambulance": null, "fire": "18", "police": "17"},
    "Chile": {"ambulance": "131", "fire": "132", "police": "133"},
    "China, The People's Republic of": {"ambulance": "120", "fire": "119", "police": "110, 122 (traffic accident)"},
    "Colombia": {"ambulance": "119", "fire": null, "police": null},
    "Comoros Islands": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Congo": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Cook Islands": {"ambulance": "998", "fire": "996", "police": "999"},
    "Costa Rica": {"ambulance": "911", "fire": null, "police": null},
    "Côte d'Ivoire": {"ambulance": null, "fire": "110, 111, 170", "police": "180"},
    "Croatia": {"ambulance": "112", "fire": null, "police": null},
    "Cuba": {"ambulance": "26811", "fire": null, "police": null},
    "Curacao": {"ambulance": "112", "fire": "114", "police": "444444"},
    "Cyprus": {"ambulance": "112", "fire": null, "police": null},
    "Czech Republic": {"ambulance": "112, 155", "fire": "150", "police": "158"},
    "Congo, Democratic Republic of": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Denmark": {"ambulance": "112", "fire": null, "police": null},
    "Djibouti": {"ambulance": "351351", "fire": "18", "police": "17"},
    "Dominica": {"ambulance": "999", "fire": null, "police": null},
    "Dominican Republic": {"ambulance": "911", "fire": null, "police": null},
    "East Timor": {"ambulance": "112", "fire": null, "police": null},
    "Easter Island": {"ambulance": "100‐215", "fire": "100‐264", "police": "100‐244"},
    "Ecuador": {"ambulance": "131", "fire": null, "police": "101"},
    "Egypt": {"ambulance": "123", "fire": "180", "police": "122"},
    "El Salvador": {"ambulance": "911", "fire": null, "police": null},
    "England": {"ambulance": "112, 999", "fire": null, "police": null},
    "Equatorial Guinea": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Eritrea": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Estonia": {"ambulance": "112", "fire": "112", "police": "110"},
    "Ethiopia": {"ambulance": "92", "fire": "93", "police": "91"},
    "Falkland Islands": {"ambulance": "999", "fire": null, "police": null},
    "Fiji": {"ambulance": "911", "fire": null, "police": null},
    "Finland": {"ambulance": "112", "fire": null, "police": null},
    "France": {"ambulance": "112, 15", "fire": "112, 18", "police": "112, 17"},
    "French Guiana": {"ambulance": "112, 15", "fire": "112, 18", "police": "112, 17"},
    "French Polynesia": {"ambulance": "15", "fire": "18", "police": "17"},
    "Gabon": {"ambulance": "1300‐1399", "fire": "18", "police": "1730"},
    "Gambia, The": {"ambulance": "16", "fire": "18", "police": "17"},
    "Georgia": {"ambulance": "022", "fire": null, "police": null},
    "Germany": {"ambulance": "112", "fire": "110", "police": null},
    "Ghana": {"ambulance": "776111‐5", "fire": "192", "police": "999, 171"},
    "Gibraltar": {"ambulance": "999", "fire": null, "police": null},
    "Greece": {"ambulance": "112, 166", "fire": "112, 199", "police": "112, 100"},
    "Grenada": {"ambulance": "434", "fire": "112", "police": "911"},
    "Guadeloupe": {"ambulance": "18", "fire": "18", "police": "17"},
    "Guam": {"ambulance": "911", "fire": null, "police": null},
    "Guatemala": {"ambulance": "123", "fire": "123", "police": "110"},
    "Guinea Bissau": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Guinea Republic": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Guyana": {"ambulance": "999", "fire": null, "police": null},
    "Haiti": {"ambulance": "118", "fire": null, "police": "114"},
    "Honduras": {"ambulance": "195, 37 8654 198", "fire": null, "police": "119"},
    "Hong Kong": {"ambulance": "999", "fire": null, "police": null},
    "Hungary": {"ambulance": "112", "fire": null, "police": null},
    "Iceland": {"ambulance": "112", "fire": null, "police": null},
    "India": {"ambulance": "102", "fire": "101", "police": "100, 103 (traffic accident)"},
    "Indonesia": {"ambulance": "118", "fire": "113", "police": "110"},
    "Iran": {"ambulance": "115", "fire": "123", "police": "110"},
    "Iraq": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Ireland, Republic of": {"ambulance": "112. 999", "fire": null, "police": null},
    "Isle of Man": {"ambulance": "999", "fire": null, "police": null},
    "Israel": {"ambulance": "101", "fire": "102", "police": "100"},
    "Italy": {"ambulance": "112, 118", "fire": "112, 115", "police": "112, 113"},
    "Jamaica": {"ambulance": "110", "fire": "110", "police": "119"},
    "Japan": {"ambulance": "119", "fire": "119", "police": "110"},
    "Jordan": {"ambulance": "191", "fire": "193", "police": "192"},
    "Kazakhstan": {"ambulance": "03", "fire": null, "police": null},
    "Kenya": {"ambulance": "999", "fire": null, "police": null},
    "Kiribati": {"ambulance": "994", "fire": null, "police": null},
    "Kosovo": {"ambulance": "94", "fire": null, "police": null},
    "Korea, The Democratic People's Republic of (North Korea)": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Korea, The Republic of (South Korea)": {"ambulance": "119", "fire": "119", "police": "112"},
    "Kuwait": {"ambulance": "777", "fire": null, "police": null},
    "Kyrgyzstan": {"ambulance": "103", "fire": null, "police": null},
    "Laos": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Latvia": {"ambulance": "112, 03", "fire": "112, 01", "police": "112, 02"},
    "Lebanon": {"ambulance": "112", "fire": null, "police": null},
    "Lesotho": {"ambulance": "121", "fire": "122", "police": "123/124"},
    "Liberia": {"ambulance": "911 (cell phones only)", "fire": null, "police": null},
    "Libya": {"ambulance": "193", "fire": null, "police": null},
    "Liechtenstein": {"ambulance": "112", "fire": null, "police": null},
    "Lithuania": {"ambulance": "112", "fire": null, "police": null},
    "Luxembourg": {"ambulance": "112/113", "fire": null, "police": null},
    "Macau": {"ambulance": "999", "fire": null, "police": null},
    "Macedonia": {"ambulance": "94", "fire": "93", "police": "92"},
    "Madagascar": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Malawi": {"ambulance": "998", "fire": "999", "police": "997"},
    "Malaysia": {"ambulance": "999", "fire": "994", "police": "999"},
    "Maldives Republic": {"ambulance": "102", "fire": "999", "police": "119"},
    "Mali": {"ambulance": "15", "fire": "17", "police": "18"},
    "Malta": {"ambulance": "112", "fire": null, "police": null},
    "Marianas Island": {"ambulance": "911", "fire": null, "police": null},
    "Marshall Islands": {"ambulance": "625 4111", "fire": null, "police": "625 8666"},
    "Martinique": {"ambulance": "15", "fire": "18", "police": "17"},
    "Mauritania": {"ambulance": "local numbers only", "fire": "118", "police": "117"},
    "Mauritius": {"ambulance": "999", "fire": null, "police": null},
    "México": {"ambulance": "065", "fire": "068", "police": "060"},
    "Micronesia, Federated States of": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Moldova": {"ambulance": "903", "fire": "901", "police": "902"},
    "Monaco": {"ambulance": "112", "fire": null, "police": null},
    "Mongolia": {"ambulance": "103", "fire": "101", "police": "102"},
    "Montenegro": {"ambulance": "94", "fire": null, "police": null},
    "Montserrat": {"ambulance": "911", "fire": null, "police": "999"},
    "Morocco": {"ambulance": "15", "fire": "15", "police": "19"},
    "Mozambique": {"ambulance": "117", "fire": "198", "police": "119"},
    "Namibia": {"ambulance": "2032276", "fire": "2032270", "police": "1011"},
    "Nauru": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Nepal": {"ambulance": "228094", "fire": null, "police": "100"},
    "Netherlands": {"ambulance": "112", "fire": null, "police": null},
    "Netherlands Antilles": {"ambulance": "112", "fire": null, "police": null},
    "New Zealand": {"ambulance": "111", "fire": null, "police": null},
    "Nicaragua": {"ambulance": "128", "fire": "115, 911", "police": "118"},
    "Niger": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Nigeria": {"ambulance": "199", "fire": null, "police": null},
    "Northern Ireland": {"ambulance": "112, 999", "fire": null, "police": null},
    "Norway": {"ambulance": "112, 110", "fire": null, "police": null},
    "Oman": {"ambulance": "999", "fire": null, "police": null},
    "Pakistan": {"ambulance": "15", "fire": null, "police": null},
    "Palau": {"ambulance": "911", "fire": null, "police": null},
    "Palestine": {"ambulance": "101", "fire": "101", "police": "100"},
    "Panama": {"ambulance": "269‐9778", "fire": "103", "police": "104"},
    "Papua New Guinea": {"ambulance": null, "fire": "110", "police": "000"},
    "Paraguay": {"ambulance": "00", "fire": null, "police": null},
    "Peru": {"ambulance": "011, 5114", "fire": null, "police": null},
    "Philippines": {"ambulance": "166, 117", "fire": null, "police": null},
    "Poland": {"ambulance": "112, 999", "fire": null, "police": null},
    "Portugal": {"ambulance": "112", "fire": null, "police": null},
    "Puerto Rico": {"ambulance": "911", "fire": null, "police": null},
    "Qatar": {"ambulance": "999", "fire": null, "police": null},
    "Réunion": {"ambulance": "112, 15 18", "fire": null, "police": "17"},
    "Romania": {"ambulance": "112", "fire": null, "police": null},
    "Russia": {"ambulance": "112", "fire": null, "police": null},
    "Rwanda": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Samoa": {"ambulance": "999", "fire": null, "police": null},
    "San Marino": {"ambulance": "113", "fire": "115", "police": "112"},
    "Sao Tome & Principe": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Saudi Arabia": {"ambulance": "997", "fire": "998", "police": "999"},
    "Scotland": {"ambulance": "112, 999", "fire": null, "police": null},
    "Senegal": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Serbia": {"ambulance": "94", "fire": null, "police": null},
    "Seychelles": {"ambulance": "151", "fire": "999", "police": "999"},
    "Sierra Leone": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Singapore": {"ambulance": "995", "fire": "995", "police": "999"},
    "Slovakia": {"ambulance": "112", "fire": null, "police": null},
    "Slovenia": {"ambulance": "112", "fire": null, "police": null},
    "Solomon Islands": {"ambulance": "911", "fire": null, "police": null},
    "Somalia": {"ambulance": "local numbers only", "fire": null, "police": null},
    "South Africa": {"ambulance": "10177", "fire": "10177", "police": "10111"},
    "Spain": {"ambulance": "112", "fire": "112", "police": "112"},
    "Sri Lanka": {"ambulance": "110", "fire": "110", "police": "119"},
    "St. Helena": {"ambulance": "911", "fire": null, "police": null},
    "St. Kitts & Nevis": {"ambulance": "911", "fire": null, "police": "911"},
    "St. Lucia": {"ambulance": "911", "fire": null, "police": null},
    "St. Pierre & Miquelon": {"ambulance": "17", "fire": "18", "police": "17"},
    "St. Vincent & Grenadines": {"ambulance": "911", "fire": null, "police": null},
    "Sudan": {"ambulance": "999", "fire": "999", "police": "999"},
    "Suriname": {"ambulance": "115", "fire": null, "police": null},
    "Swaziland": {"ambulance": "933", "fire": "933", "police": "999"},
    "Sweden": {"ambulance": "112", "fire": null, "police": null},
    "Switzerland": {"ambulance": "112, 144", "fire": "112, 118", "police": "112, 117"},
    "Syria": {"ambulance": "110", "fire": "113", "police": "112"},
    "Taiwan": {"ambulance": "119", "fire": "119", "police": "110"},
    "Tajikistan": {"ambulance": "03", "fire": null, "police": null},
    "Tanzania": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Thailand": {"ambulance": "1554", "fire": "199", "police": "191"},
    "Togo": {"ambulance": "8200", "fire": null, "police": null},
    "Tonga": {"ambulance": "911", "fire": null, "police": null},
    "Trinidad & Tobago": {"ambulance": "990", "fire": "990", "police": "999"},
    "Tunisia": {"ambulance": "190", "fire": "198", "police": "197"},
    "Turkey": {"ambulance": "112", "fire": "110", "police": "155"},
    "Turkmenistan": {"ambulance": "03", "fire": null, "police": null},
    "Turks & Caicos Islands": {"ambulance": "999", "fire": null, "police": null},
    "Tuvalu": {"ambulance": "911", "fire": null, "police": null},
    "Uganda": {"ambulance": "local numbers only", "fire": null, "police": null},
    "Ukraine": {"ambulance": "03", "fire": "01", "police": "02"},
    "United Arab Emirates": {"ambulance": "998", "fire": "997", "police": "999"},
    "United Kingdom": {"ambulance": "112, 999", "fire": null, "police": null},
    "United States of America": {"ambulance": "911", "fire": null, "police": null},
    "Uruguay": {"ambulance": "911", "fire": "104", "police": "101"},
    "Uzbekistan": {"ambulance": "03", "fire": null, "police": null},
    "Vanuatu": {"ambulance": "112, 115", "fire": "112, 112", "police": "112, 113"},
    "Venezuela": {"ambulance": "171", "fire": "171", "police": "171"},
    "Vietnam": {"ambulance": "115", "fire": "114", "police": "113"},
    "Virgin Islands": {"ambulance": "911", "fire": null, "police": null},
    "Wales": {"ambulance": "112, 999", "fire": null, "police": null},
    "Wallis & Futuna": {"ambulance": "15", "fire": "18", "police": "17"},
    "Western Samoa": {"ambulance": "994", "fire": "995", "police": "995"},
    "Yemen": {"ambulance": "191", "fire": null, "police": null},
    "Yugoslavia": {"ambulance": "94", "fire": null, "police": null},
    "Zambia": {"ambulance": "999", "fire": null, "police": "991"},
    "Zimbabwe": {"ambulance": "999", "fire": null, "police": "995"}
}

export const getHelpLines = (country) => {
    const countryNumbers = emergencyNumbers[country];
    if (!countryNumbers) {
        return {
            ambulance: null,
            fire: null,
            police: null
        };
    }

    return countryNumbers;
}