// export const symptomsOptions = [
//     { key: "headaches", value: "headaches", text: "headaches" }, // doube
//     { key: "myalgia", value: "myalgia", text: "myalgia" },
//     { key: "vomit", value: "vomit", text: "vomit" },
//     { key: "sore throat", value: "sore throat", text: "sore throat" }, // double
//     { key: "sweaty", value: "sweaty", text: "sweaty" },
//     { key: "thirsty", value: "thirsty", text: "thirsty" },
//     { key: "tired", value: "tired", text: "tired" },
//     { key: "weak", value: "weak", text: "weak" },
//     { key: "chills", value: "chills", text: "chills" },
//     { key: "fever", value: "fever", text: "fever" },
//     { key: "tingl", value: "tingl", text: "tingl" },
//     { key: "numbness", value: "numbness", text: "numbness" },//double
//     { key: "electricTweaks", value: "electric tweaks", text: "electric tweaks" },
//     { key: "light- headed", value: "light-headed", text: "light headed" },
//     { key: "dizzy", value: "dizzy", text: "dizzy" },
//     { key: "black out", value: "black out", text: "black out" },
//     { key: "sick", value: "sick", text: "sick" },
//     { key: "flu", value: "flu", text: "flu" },
//     { key: "sleepy", value: "sleepy", text: "sleepy" },
//     { key: "blindness", value: "blindness", text: "blindness" },
//     { key: "nausea", value: "nausea", text: "nausea" },
//     { key: "footPain", value: "footPain", text: "foot pain" },
//     { key: "rash", value: "rash", text: "rash" },
//     { key: "dry skin", value: "dry skin", text: "dry skin" },
//     { key: "short of breath", value: "short of breath", text: "short of breath" },
//     { key: "mouth is dry", value: "mouth is dry", text: "dry mouth" }, // change to mouth
//     { key: "room spinning around me", value: "room spinning around me", text: "room spinning" },
//     { key: "blurred vision", value: "blurred vision", text: "blurred vision" },
//     { key: "double vision", value: "double vision", text: "double vision" },
//     { key: "smell things", value: "smell things", text: "loss of smell" },
//     { key: "excrete solid feces", value: "excrete solid feces", text: "excrete solid feces" }, // chnages
//     { key: "scratching", value: "scratching", text: "scratching" }, //change
//     { key: "sweating", value: "sweating", text: "sweating" }, // changes
//     { key: "Swallow", value: "Swallow", text: "swallow" }, // changes
//     { key: "taste", value: "taste", text: "loss of taste" },
//     { key: "abdominal pain", value: "abdominal pain", text: "abdominal pain" },
//     { key: "blood in stool", value: "blood in stool", text: "blood in stool" },
//     { key: "chest pain", value: "chest pain", text: "chest pain" },
//     { key: "constipation", value: "constipation", text: "constipation" },
//     { key: "cough", value: "cough", text: "cough" },
//     { key: "diarrhea", value: "diarrhea", text: "diarrhea" },
//     { key: "difficulty swallowing", value: "difficulty swallowing", text: "difficulty swallowing" }, // change
//     { key: "eye discomfort", value: "eye discomfort", text: "eye discomfort" },
//     { key: "eye redness", value: "eye redness", text: "eye redness" },
//     { key: "eye problems", value: "eye problems", text: "eye problems" },
//     { key: "ankle pain", value: "ankle pain", text: "ankle pain" },
//     { key: "foot swelling", value: "foot swelling", text: "foot swelling" },
//     { key: "leg swelling", value: "leg swelling", text: "leg swelling" },
//     { key: "hip pain", value: "hip pain", text: "hip pain" },
//     { key: "knee pain", value: "knee pain", text: "knee pain" },
//     { key: "low back pain", value: "low back pain", text: "low back pain" },
//     { key: "nasal congestion", value: "nasal congestion", text: "nasal congestion" },
//     { key: "congestion", value: "congestion", text: "congestion" },
//     { key: "neck pain", value: "neck pain", text: "neck pain" },
//     { key: "pelvic pain", value: "pelvic pain", text: "pelvic pain" },
//     { key: "shoulder pain", value: "shoulder pain", text: "shoulder pain" },
//     { key: "urinary problems", value: "urinary problems", text: "urinary problems" },
//     { key: "wheezing", value: "wheezing", text: "wheezing" },
//     { key: "joint pain", value: "joint pain", text: "joint pain" },
//     { key: "muscle pain", value: "muscle pain", text: "muscle pain" },
//     { key: "ankle problems", value: "ankle problems", text: "ankle problems" },
//     { key: "back Problems", value: "back Problems", text: "back problems" },// fix
//     { key: "bowel incontinence", value: "bowel incontinence", text: "bowel incontinence" },
//     { key: "calf problems", value: "calf problems", text: "calf problems" },
//     { key: "catarrh", value: "catarrh", text: "catarrh" },
//     { key: "cold sore", value: "cold sore", text: "cold sore" },
//     { key: "dehydration", value: "dehydration", text: "dehydration" },
//     { key: "lightheadedness", value: "lightheadedness", text: "lightheadedness" },
//     { key: "barache", value: "barache", text: "barache" },
//     { key: "elbow problems", value: "elbow problems", text: "elbow problems" },
//     { key: "farting", value: "farting", text: "farting" },
//     { key: "globus", value: "globus", text: "globus" },
//     { key: "foot problems", value: "foot problems", text: "foot problems" },
//     { key: "genital symptoms", value: "genital symptoms", text: "genital symptoms" },
//     { key: "hay fever", value: "hay fever", text: "hay fever" },
//     { key: "hearing loss", value: "hearing loss", text: "hearing loss" },
//     { key: "hip problems", value: "hip problems", text: "hip problems" },
//     { key: "itching", value: "itching", text: "itching" },
//     { key: "itchy bottom", value: "itchy bottom", text: "itchy bottom" },
//     { key: "indigestion", value: "indigestion", text: "indigestion" },
//     { key: "migraine", value: "migraine", text: "migraine" },
//     { key: "neck problems", value: "neck problems", text: "neck problems" },
//     { key: "nosebleed", value: "nosebleed", text: "nosebleed" },
//     { key: "skin rashes in children", value: "skin rashes in children", text: "skin rashes in children" },
//     { key: "shoulder problems", value: "shoulder problems", text: "shoulder problems" },
//     { key: "swollen glands", value: "swollen glands", text: "swollen glands" },
//     { key: "testicular lumps", value: "testicular lumps", text: "testicular lumps" },
//     { key: "swell", value: "swell", text: "swelling" },
//     { key: "thigh problems", value: "thigh problems", text: "thigh problems" },
//     { key: "tinnitus", value: "tinnitus", text: "tinnitus" },
//     { key: "toothache", value: "toothache", text: "toothache" },
//     { key: "urinary tract infection", value: "urinary tract infection", text: "urinary tract infection" },
//     { key: "vertigo", value: "vertigo", text: "vertigo" },
//     { key: "warts", value: "warts", text: "warts" },
//     { key: "verrucas", value: "verrucas", text: "verrucas" },
//     { key: "wrist problem", value: "wrist problem", text: "wrist problem" },
//     { key: "finger problems", value: "finger problems", text: "finger problems" },
//     { key: "loss of appetite", value: "loss of appetite", text: "loss of appetite" },
//     { key: "weight loss", value: "weight loss", text: "weight loss" },
//     { key: "weight gain", value: "weight gain", text: "weight gain" },
//     { key: "fatigue", value: "fatigue", text: "fatigue" },
//     { key: "malaise", value: "malaise", text: "malaise" },
//     { key: "asthenia", value: "asthenia", text: "asthenia" },
//     { key: "pyrexia", value: "pyrexia", text: "pyrexia" },
//     { key: "cachexia", value: "cachexia", text: "cachexia" },
//     { key: "pain", value: "pain", text: "pain" },
//     { key: "bruising", value: "bruising", text: "bruising" },
//     { key: "jaundice", value: "jaundice", text: "jaundice" },
//     { key: "dyspareunia", value: "dyspareunia", text: "dyspareunia" },
//     { key: "vaginismus", value: "vaginismus", text: "vaginismus" },
//     { key: "tremor", value: "tremor", text: "tremor" },
//     { key: "epistaxis", value: "epistaxis", text: "epistaxis" },
//     { key: "paralysis", value: "paralysis", text: "paralysis" },
//     { key: "convulsions", value: "convulsions", text: "convulsions" },
//     { key: "syncope", value: "syncope", text: "syncope" },
//     { key: "cataplexy", value: "cataplexy", text: "cataplexy" },
//     { key: "muscle cramps", value: "muscle cramps", text: "muscle cramps" },
//     { key: "vaginal discharge", value: "vaginal discharge", text: "vaginal discharge" },
//     { key: "muscle weakness", value: "muscle weakness", text: "muscle weakness" },
//     { key: "fecal incontinence", value: "fecal incontinence", text: "fecal incontinence" },
//     { key: "hypothermia", value: "hypothermia", text: "hyperthermia" },
//     { key: "neurological", value: "neurological", text: "neurological" },
//     { key: "psychological", value: "psychological", text: "psychological" },
//     { key: "anxiety", value: "anxiety", text: "anxiety" },
//     { key: "catatonia", value: "catatonia", text: "catatonia" },
//     { key: "dysarthria", value: "dysarthria", text: "dysarthria" },
//     { key: "somnolence", value: "somnolence", text: "somnolence" },
//     { key: "insomnia", value: "insomnia", text: "insomnia" },
//     { key: "ocular", value: "ocular", text: "ocular" },
//     { key: "amaurosis fugax", value: "amaurosis fugax", text: "amaurosis fugax" },
//     { key: "amaurosis", value: "amaurosis", text: "amaurosis" },
//     { key: "mydriasis", value: "mydriasis", text: "mydriasis" },
//     { key: "miosis", value: "miosis", text: "miosis" },
//     { key: "nystagmus", value: "nystagmus", text: "nystagmus" },
//     { key: "gastrointestinal", value: "gastrointestinal", text: "gastrointestinal" },
//     { key: "anorexia", value: "anorexia", text: "anorexia" },
//     { key: "bloating", value: "bloating", text: "bloating" },
//     { key: "melena", value: "melena", text: "melena" },
//     { key: "dyspepsia", value: "dyspepsia", text: "dyspepsia" },
//     { key: "hematochezia", value: "hematochezia", text: "hematochezia" },
//     { key: "flatulence", value: "flatulence", text: "flatulence" },
//     { key: "pyrosis", value: "pyrosis", text: "pyrosis" },
//     { key: "dysphagia", value: "dysphagia", text: "dysphagia" },
//     { key: "cardiovascular", value: "cardiovascular", text: "cardiovascular" },
//     { key: "claudication", value: "claudication", text: "claudication" },
//     { key: "palpitation", value: "palpitation", text: "palpitation" },
//     { key: "bradycardia", value: "bradycardia", text: "bradycardia" },
//     { key: "tachycardia", value: "tachycardia", text: "tachycardia" },
//     { key: "arrhythmia", value: "arrhythmia", text: "arrhythmia" },
//     { key: "reticulocytosis", value: "reticulocytosis", text: "reticulocytosis" },
//     { key: "macrocytosis", value: "macrocytosis", text: "macrocytosis" },
//     { key: "urologic", value: "urologic", text: "urologic" },
//     { key: "dysuria", value: "dysuria", text: "dysuria" },
//     { key: "polyuria", value: "polyuria", text: "polyuria" },
//     { key: "hematuria", value: "hematuria", text: "hematuria" },
//     { key: "urinary frequency", value: "urinary frequency", text: "urinary frequency" },
//     { key: "impotence", value: "impotence", text: "impotence" },
//     { key: "pulmonary", value: "pulmonary", text: "pulmonary" },
//     { key: "hypoventilation", value: "hypoventilation", text: "hypoventilation" },
//     { key: "bradypnea", value: "bradypnea", text: "bradypnea" },
//     { key: "apnea", value: "apnea", text: "apnea" },
//     { key: "dyspnea", value: "dyspnea", text: "dyspnea" },
//     { key: "hemoptysis", value: "hemoptysis", text: "hemoptysis" },
//     { key: "edema", value: "edema", text: "edema" },
//     { key: "pleuritic chest pain", value: "pleuritic chest pain", text: "pleuritic chest pain" },
//     { key: "sputum production", value: "sputum production", text: "sputum production" },
//     { key: "tachypnea", value: "tachypnea", text: "tachypnea" },
//     { key: "integumentary", value: "integumentary", text: "integumentary" },
//     { key: "anasarca", value: "anasarca", text: "anasarca" },
//     { key: "blister", value: "blister", text: "blister" },
//     { key: "urticaria", value: "urticaria", text: "urticaria" },
//     { key: "paresthesia", value: "paresthesia", text: "paresthesia" },
//     { key: "infection", value: "infection", text: "infection" },
//     { key: "sinus", value: "sinus", text: "sinus" },
//     { key: "acute respiratory infection", value: "acute respiratory infection", text: "acute respiratory infection" },
//     { key: "respiratory infection", value: "respiratory infection", text: "respiratory infection" },
//     { key: "seizures", value: "seizures", text: "seizures" },
//     { key: "dizziness", value: "dizziness", text: "dizziness" },
//     { key: "drowsiness", value: "drowsiness", text: "drowsiness" },
//     { key: "pneumonia", value: "pneumonia", text: "pneumonia" },
//     { key: "encephalitis", value: "encephalitis", text: "encephalitis" },
//     { key: "acute encephalitis", value: "acute encephalitis", text: "acute encephalitis" },
//     { key: "fatal encephalitis", value: "fatal encephalitis", text: "fatal encephalitis" },
//     { key: "altered consciousness", value: "altered consciousness", text: "altered consciousness" },
//     { key: "aseptic meningitis", value: "aseptic meningitis", text: "aseptic meningitis" },
//     { key: "muscle ache", value: "muscle ache", text: "muscle ache" },
//     { key: "respiratory problems", value: "respiratory problems", text: "respiratory problems" },
//     { key: "respiratory distress", value: "respiratory distress", text: "respiratory distress" },
//     { key: "neurological signs", value: "neurological signs", text: "neurological issues" },
// ]


export const symptomsOptions = [
  "abdominal pain",
  "acute encephalitis",
  "acute respiratory infection",
  "amaurosis",
  "amaurosis fugax",
  "anasarca",
  "ankle pain",
  "ankle problems",
  "anorexia",
  "anxiety",
  "apnea",
  "arrhythmia",
  "asthenia",
  "back problems",
  "barache",
  "blood in stool",
  "blister",
  "bloating",
  "blood in stool",
  "black out",
  "blindness",
  "bowel incontinence",
  "bradycardia",
  "bradypnea",
  "bruising",
  "cataplexy",
  "catarrh",
  "catatonia",
  "catatonia",
  "cachexia",
  "calf problems",
  "cardiovascular",
  "chest pain",
  "chills",
  "claudication",
  "cold sore",
  "constipation",
  "congestion",
  "convulsions",
  "cough",
  "dizziness",
  "double vision",
  "dry mouth",
  "dry skin",
  "drowsiness",
  "dysarthria",
  "dyspareunia",
  "dyspepsia",
  "dysphagia",
  "dyspnea",
  "dysuria",
  "electric tweaks",
  "elbow problems",
  "encephalitis",
  "epistaxis",
  "excrete solid feces",
  "eye discomfort",
  "eye problems",
  "eye redness",
  "fatigue",
  "farting",
  "fever",
  "finger problems",
  "flatulence",
  "flu",
  "foot pain",
  "foot problems",
  "foot swelling",
  "gastrointestinal",
  "genital symptoms",
  "globus",
  "hay fever",
  "headaches",
  "hearing loss",
  "hematuria",
  "hematochezia",
  "hemoptysis",
  "hip pain",
  "hip problems",
  "hypoventilation",
  "hyperthermia",
  "impotence",
  "infection",
  "indigestion",
  "insomnia",
  "itching",
  "itchy bottom",
  "jaundice",
  "joint pain",
  "knee pain",
  "leg swelling",
  "light headed",
  "lightheadedness",
  "loss of appetite",
  "loss of smell",
  "loss of taste",
  "low back pain",
  "macrocytosis",
  "malaise",
  "melena",
  "migraine",
  "miosis",
  "muscle ache",
  "muscle cramps",
  "muscle pain",
  "muscle weakness",
  "myalgia",
  "mydriasis",
  "nasal congestion",
  "nausea",
  "neck pain",
  "neck problems",
  "neurological",
  "neurological issues",
  "numbness",
  "nystagmus",
  "ocular",
  "pain",
  "palpitation",
  "paresthesia",
  "pelvic pain",
  "pleuritic chest pain",
  "polyuria",
  "pneumonia",
  "psychological",
  "pyrexia",
  "pyrosis",
  "rash",
  "respiratory distress",
  "respiratory problems",
  "respiratory infection",
  "reticulocytosis",
  "room spinning",
  "seizures",
  "shoulder pain",
  "shoulder problems",
  "short of breath",
  "sinus",
  "skin rashes in children",
  "sick",
  "sore throat",
  "sputum production",
  "sweating",
  "sweaty",
  "swelling",
  "swollen glands",
  "syncope",
  "tachycardia",
  "tachypnea",
  "testicular lumps",
  "thigh problems",
  "thirsty",
  "tingl",
  "tinnitus",
  "toothache",
  "tired",
  "tremor",
  "urinary frequency",
  "urinary problems",
  "urinary tract infection",
  "urologic",
  "urticaria",
  "vaginal discharge",
  "vaginismus",
  "vomit",
  "warts",
  "weight gain",
  "weight loss",
  "weak",
  "weakness",
  "wheezing",
  "wrist problem"
]















